package main

import (
	"fmt"

	"github.com/GGBTC/explorer/btc"
)

func main() {
	//ltctxid := "af6af508082dd96714bb03129364abe77ddd422091827bd21343541140bebefb"
	//btctxid := "af6af508082dd96714bb03129364abe77ddd422091827bd21343541140bebefb"
	//res := ltc.CatchUpBlockss()
	res := btc.CatchUpBlockss()
	fmt.Println(res)

}

type AutoGenerated1 struct {
	Txid      string `json:"txid"`
	Blockhash string `json:"blockhash"`
	Blocktime int    `json:"blocktime"`
	Version   int    `json:"version"`
	Vin       []struct {
		Txid     string `json:"txid"`
		Index    int    `json:"index"`
		Address  string `json:"address"`
		Currency string `json:"currency"`
		Value    int    `json:"value"`
	} `json:"vin"`
	Vout []struct {
		N         int    `json:"n"`
		Addresses string `json:"addresses"`
		Value     int    `json:"value"`
		Type      string `json:"type"`
		Currency  string `json:"currency"`
	} `json:"vout"`
}

type AutoGenerated struct {
	TxID        string `json:"TxID"`
	BlockHash   string `json:"block_hash"`
	BlockHeight int    `json:"block_height"`
	BlockTime   int    `json:"block_time"`
	Vin         []struct {
		Prevout  string `json:"prevout"`
		Address  string `json:"address"`
		Value    int64  `json:"value"`
		Currency string `json:"currency"`
		Index    int64
	} `json:"Vin"`
	Vout []struct {
		Address  string `json:"address"`
		Value    int64  `json:"value"`
		Index    int    `json:"index"`
		Currency string `json:"currency"`
	} `json:"Vout"`
}
